// Vérification du lead : le relâchement de PLONGER pendant que le joystick est tenu est-il vu ?
// Compare deux façons d'envoyer le relâchement d'UN doigt en CDP : touchMove sans le point
// (ce que fait tools/e2e/qa/pilot.mjs) et touchEnd complet puis ré-appui du joystick.
//   PORT=8826 node tools/polish/lead/release-check.mjs
import { ORIGIN, launch, newContext, sleep, waitFor, state, newPhone, joinPhone, center } from '../../e2e/qa/lib.mjs'

const browser = await launch()
const pcCtx = await newContext(browser)
const pc = await pcCtx.newPage()
await pc.goto(`${ORIGIN}/?debug=nosave`, { waitUntil: 'load' })
await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'title' && !!window.__ombres?.useLobby.getState().joinUrl, null, 120000, 'titre + salle')
const s = await state(pc)
const u = new URL(s.joinUrl)
const A = await newPhone(browser, 'iPhone 15 Pro', 'iphone')
await joinPhone(A, `${ORIGIN}${u.pathname}${u.search}`, 'Test', 3)
await waitFor(pc, () => window.__ombres?.runner.phase === 'lobby', null, 8000, 'salon')
await sleep(1500)
const tp = (id, x, y) => ({ x, y, id, radiusX: 6, radiusY: 6, force: 1 })
const send = (type, pts) => A.cdp.send('Input.dispatchTouchEvent', { type, touchPoints: pts })
const isDown = () => A.page.evaluate(() => document.querySelector('.act--dive')?.classList.contains('is-down'))
const zone = await center(A.page, '.stick-zone')
const d = await center(A.page, '.act--dive')
const stick = tp(1, zone.b.x + zone.b.width * 0.45, zone.b.y + zone.b.height * 0.55)
await send('touchStart', [stick])
await sleep(100)
await send('touchStart', [stick, tp(2, d.x, d.y)])
await sleep(300)
console.log('A. après appui PLONGER, is-down =', await isDown())
await send('touchMove', [stick])
await sleep(300)
console.log('A. après touchMove sans le doigt 2 (méthode pilot.mjs), is-down =', await isDown())
await send('touchEnd', [])
await sleep(300)
console.log('A. après touchEnd complet, is-down =', await isDown())
// B : relâchement par touchEnd portant les points restants
await send('touchStart', [stick])
await sleep(100)
await send('touchStart', [stick, tp(2, d.x, d.y)])
await sleep(300)
console.log('B. après appui PLONGER, is-down =', await isDown())
await send('touchEnd', [stick])
await sleep(300)
console.log('B. après touchEnd [stick] (méthode steer de lib.mjs), is-down =', await isDown())
await send('touchEnd', [])
await browser.close()
