// QA technique : plein écran (touche F) au titre et en manche : état, taille du canvas, réglage synchronisé.
import { launch, newContext } from '../../lib/browser.mjs'
import { ORIGIN, SHOTS, sleep, waitFor, presetSettings, lobbyWith, startMatch, collect } from './common.mjs'
const browser = await launch()
const ctx = await newContext(browser, { w: 1600, h: 900 })
const pc = await ctx.newPage()
const logs = collect(pc, 'pc')
await presetSettings(pc, { lang: 'fr', quality: 'medium', narrator: 'off' })
await pc.goto(`${ORIGIN}/?debug=nosave`, { waitUntil: 'load' })
await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'title', null, 120000, 'titre')
const st = () => pc.evaluate(() => ({ fs: !!document.fullscreenElement, inner: `${innerWidth}x${innerHeight}`, canvas: `${document.querySelector('canvas').width}x${document.querySelector('canvas').height}` }))
console.log('titre', JSON.stringify(await st()))
await pc.keyboard.press('KeyF')
await sleep(800)
console.log('après F', JSON.stringify(await st()))
await lobbyWith(pc, 4, { rounds: 1 }).catch(() => {})
await pc.keyboard.press('KeyF')
await sleep(800)
console.log('salon, après F', JSON.stringify(await st()))
await pc.keyboard.press('KeyF')
await sleep(800)
await startMatch(pc)
await sleep(2000)
await pc.keyboard.press('KeyF')
await sleep(800)
console.log('manche, après F (joueur clavier présent)', JSON.stringify(await st()), 'phase', await pc.evaluate(() => window.__ombres.runner.phase))
console.log(logs.slice(0, 5).join('\n'))
await browser.close()
