// Fumée : chargement → titre → salon, captures et console.
//   node tools/e2e/smoke.mjs [--q=?debug]
import { ORIGIN, launch, newContext, collectLogs, gpuRenderer, shotDir, shot, sleep, waitFor, state, errorsOf } from './lib.mjs'

const dir = shotDir('smoke')
const browser = await launch()
const ctx = await newContext(browser)
const page = await ctx.newPage()
const logs = collectLogs(page)
await page.goto(`${ORIGIN}/?debug`, { waitUntil: 'load' })
console.log('gpu', await gpuRenderer(page))
await sleep(1200)
await shot(page, dir, 'loading')
await waitFor(page, () => window.__ombres?.useUi.getState().screen === 'title', null, 60000, 'titre')
await sleep(2500)
await shot(page, dir, 'title')
await page.keyboard.press('KeyG')
await sleep(1500)
await shot(page, dir, 'title-menu')
await page.keyboard.press('Enter')
await waitFor(page, () => window.__ombres?.useUi.getState().screen === 'lobby', null, 10000, 'salon')
await sleep(2500)
await shot(page, dir, 'lobby')
await page.keyboard.press('Space')
await sleep(2500)
await shot(page, dir, 'lobby-kb')
console.log(JSON.stringify(await state(page), null, 1))
console.log('erreurs', errorsOf(logs))
console.log(logs.slice(-25).join('\n'))
await browser.close()
