// Revue DA : écrans d'interface du PC — menu, réglages, crédits (plusieurs instants), pause en manche,
// salon à 1 joueur clavier (quitter ?), téléphone en portrait.
//   PORT=8821 node tools/polish/art/screens.mjs [--name=screens] [--lang=fr]
import { ORIGIN, launch, newContext, collectLogs, sleep, waitFor, problems, arg, presetSettings } from '../../e2e/qa/lib.mjs'
import { mkdirSync } from 'node:fs'
import { join } from 'node:path'

const NAME = arg('name', 'screens')
const LANG = arg('lang', 'fr')
const dir = join(import.meta.dirname, '../../../shots/polish/art', NAME)
mkdirSync(dir, { recursive: true })
let n = 0
const shot = async (page, label) => {
  const f = join(dir, `${String(++n).padStart(3, '0')}-${label}.jpg`)
  await page.screenshot({ path: f, type: 'jpeg', quality: 82 })
}
const browser = await launch()
const ctx = await newContext(browser)
const pc = await ctx.newPage()
const logs = collectLogs(pc)
await presetSettings(pc, { lang: LANG })
await pc.goto(`${ORIGIN}/?debug=nosave`, { waitUntil: 'load' })
await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'title', null, 120000, 'titre')
await sleep(6000)
await pc.keyboard.press('KeyX')
await sleep(900)
await shot(pc, 'menu')
await pc.keyboard.press('ArrowDown')
await sleep(200)
await pc.keyboard.press('Enter')
await sleep(900)
await shot(pc, 'settings')
await pc.keyboard.press('ArrowDown')
await sleep(150)
await pc.keyboard.press('ArrowDown')
await sleep(300)
await shot(pc, 'settings-focus')
await pc.keyboard.press('Escape')
await sleep(600)
await pc.keyboard.press('ArrowDown')
await sleep(200)
await pc.keyboard.press('Enter')
for (const t of [1500, 5000, 9000, 14000]) {
  await sleep(t === 1500 ? 1500 : 4500)
  await shot(pc, `credits-${t}`)
}
await pc.keyboard.press('Escape')
await sleep(1500)
await pc.keyboard.press('Enter')
await sleep(500)
await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'lobby', null, 15000, 'salon')
await sleep(800)
await pc.keyboard.press('Space')
await sleep(1500)
await shot(pc, 'lobby-kb')
await pc.keyboard.press('Escape')
await sleep(900)
await shot(pc, 'lobby-kb-escape')
const sc = await pc.evaluate(() => window.__ombres.useUi.getState().screen)
console.log('après Échap au salon :', sc)
if (sc === 'lobby') {
  await pc.keyboard.press('Enter')
  await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'rules', null, 8000, 'cartes')
  await sleep(800)
  await pc.keyboard.press('Enter')
  await waitFor(pc, () => window.__ombres?.useUi.getState().screen === 'game', null, 8000, 'manche')
  await waitFor(pc, () => (window.__ombres?.runner.sim?.state.sun.t ?? -9) > 6, null, 30000, 't>6')
  await pc.keyboard.press('Escape')
  await sleep(1000)
  await shot(pc, 'pause')
  await pc.keyboard.press('ArrowDown')
  await sleep(200)
  await pc.keyboard.press('Enter')
  await sleep(900)
  await shot(pc, 'pause-settings')
  await pc.keyboard.press('Escape')
  await sleep(500)
  await pc.keyboard.press('Escape')
  await sleep(800)
}
// téléphone en portrait
const pctx = await newContext(browser, { mobile: 'iPhone 15 Pro' })
const ph = await pctx.newPage()
const join0 = await pc.evaluate(() => window.__ombres.useLobby.getState().joinUrl)
const u = new URL(join0)
await ph.goto(`${ORIGIN}${u.pathname}${u.search}`, { waitUntil: 'load' })
await sleep(3000)
await shot(ph, 'phone-portrait-join')
const errs = problems(logs)
console.log(errs.length ? `PROBLÈMES :\n${errs.join('\n')}` : 'console propre')
await browser.close()
