import type { StringTable } from './index.ts'

// Chaînes du domaine « host » (écrans et HUD du PC). Clés préfixées par « host. ».
// Règle des noms de couleur (GDD §16.2) : {name} est un nom propre, sans article,
// jamais suivi d'un adjectif ou participe accordé.
export const host: StringTable = {
  fr: {
    // ─── Commun ───
    'host.back': 'Retour',
    'host.close': 'Fermer',
    'host.yes': 'Oui',
    'host.no': 'Non',
    // ─── Secours (game, G6) : pas de WebGL 2, erreur d'affichage ───
    'host.webgl.title': 'Ombres a besoin de WebGL 2',
    'host.webgl.body': 'Active l’accélération matérielle dans les réglages du navigateur, puis recharge la page.',
    'host.error.body': 'L’affichage s’est interrompu. Recharge : la partie reprendra où elle en était.',
    'host.error.reload': 'Recharger',
    'host.key.space': 'Espace',
    'host.key.enter': 'Entrée',
    'host.key.esc': 'Échap',
    'host.key.shift': 'Maj',
    'host.key.altgr': 'AltGr',
    'host.key.arrows': 'Flèches',
    'host.key.tab': 'Tab',
    'host.key.altRight': 'Alt droit',
    'host.key.shiftRight': 'Maj droite',
    'host.key.numpadEnter': 'Entrée du pavé',
    'host.key.numpad0': '0 du pavé',
    'host.key.semicolon': 'Point-virgule',
    'host.key.comma': 'Virgule',
    'host.key.period': 'Point',
    'host.key.colon': 'Deux-points',
    'host.key.slash': 'Barre oblique',
    'host.key.quote': 'Apostrophe',
    'host.key.bracket': 'Crochet',
    'host.key.minus': 'Moins',
    'host.key.equal': 'Égal',

    // ─── Chargement ───
    'host.loading.start': 'Préparation du désert…',
    'host.loading.fonts': 'Encrage des lettres…',
    'host.loading.textures': 'Ratissage du sable…',
    'host.loading.models': 'Réveil des oiseaux…',
    'host.loading.sounds': 'Accordage du vent…',
    'host.loading.voices': 'Le conteur s’éclaircit la voix…',
    'host.loading.shaders': 'Mélange des couleurs…',
    'host.loading.world': 'Le soleil se lève…',
    'host.loading.done': 'Le désert est prêt.',
    'host.loading.tagline': 'Ton ombre peint le désert.',

    // ─── Titre ───
    'host.title.pressAny': 'Appuie sur une touche',
    'host.title.play': 'Jouer',
    'host.title.settings': 'Réglages',
    'host.title.credits': 'Crédits',
    'host.title.players': '1 à 12 joueurs · un téléphone chacun',
    'host.title.scan': 'Scanne pour jouer',

    // ─── Salon ───
    'host.lobby.title': 'Le salon',
    'host.lobby.join': 'Rejoindre',
    'host.lobby.scan': 'Scanne avec ton téléphone',
    'host.lobby.orVisit': 'ou ouvre',
    'host.lobby.code': 'Code de salle',
    'host.lobby.connecting': 'Ouverture de la salle…',
    'host.lobby.offline': 'Serveur injoignable, nouvel essai…',
    'host.lobby.keyboardJoin': 'pour jouer au clavier',
    'host.lobby.keyboardJoin2': 'pour un 2e joueur au clavier',
    'host.lobby.players': 'Les oiseaux',
    'host.lobby.waiting': 'Le désert attend ses oiseaux.',
    'host.lobby.waitingSub': 'Scanne le code : ton oiseau s’envole ici.',
    'host.lobby.freeSeat': 'Place libre',
    'host.lobby.addBot': 'Ajouter un bot',
    'host.lobby.removeBot': 'Retirer ce bot',
    'host.lobby.changeBot': 'Changer de caractère',
    'host.lobby.botLevel': 'Niveau',
    'host.lobby.ready': 'Prêt',
    'host.lobby.trained': 'Entraîné',
    'host.lobby.substitute': 'remplaçant',
    'host.lobby.disconnected': 'hors ligne',
    'host.lobby.assist': 'Aide au vol',
    'host.lobby.kind.phone': 'Téléphone',
    'host.lobby.kind.keyboard': 'Clavier {n}',
    'host.lobby.kind.bot': 'Bot',
    'host.lobby.start': 'Lancer',
    'host.lobby.needPlayer': 'Il faut au moins un joueur',
    'host.lobby.rules': 'Les règles',
    'host.lobby.full': 'Complet',
    'host.lobby.dummy': 'Mannequin',
    'host.lobby.kbSteer': 'diriger',
    'host.lobby.kbDive': 'plonger',
    'host.lobby.kbFlap': 'coup d’aile',
    'host.lobby.kbQuit': 'quitter',
    'host.lobby.kbGoal.fly': 'Objectif : vole un peu',
    'host.lobby.kbGoal.dive': 'Objectif : maintiens {dive}',
    'host.lobby.kbGoal.strike': 'Objectif : pique le mannequin',
    'host.lobby.kbGoal.done': 'Prêt : Entrée pour lancer',
    'host.goal.fly': 'Vole',
    'host.goal.dive': 'Plonge',
    'host.goal.strike': 'Pique',

    // ─── Réglages de partie ───
    'host.match.settings': 'La partie',
    'host.match.rounds': 'Manches',
    'host.match.length': 'Durée',
    'host.match.length.short': 'Courte',
    'host.match.length.normal': 'Normale',
    'host.match.length.long': 'Longue',
    'host.match.botLevel': 'Bots',
    'host.match.lastDouble': 'Dernière manche ×2',

    // ─── Bots ───
    'host.bot.falcon': 'Faucon',
    'host.bot.ploughman': 'Laboureur',
    'host.bot.magpie': 'Pie',
    'host.bot.nomad': 'Nomade',
    'host.bot.lookout': 'Guetteur',
    'host.bot.fool': 'Fou',
    'host.bot.watchmaker': 'Horloger',
    'host.botDesc.falcon': 'chasse d’en haut',
    'host.botDesc.ploughman': 'laboure au ras du sable',
    'host.botDesc.magpie': 'pille la couronne',
    'host.botDesc.nomad': 'balaie en longues lignes',
    'host.botDesc.lookout': 'guette à l’ombre des tours',
    'host.botDesc.fool': 'imprévisible',
    'host.botDesc.watchmaker': 'scelle son sable avant la nuit',
    'host.botLevel.0': 'Oisillon',
    'host.botLevel.1': 'Voyageur',
    'host.botLevel.2': 'Seigneur des sables',

    // ─── Cartes des règles ───
    'host.rules.title': 'Trois règles pour commencer',
    'host.rules.1': 'Ton ombre peint le sable. À la nuit, on compte.',
    'host.rules.2': 'Bas : fort. Haut : grand. Le fort recouvre le pâle.',
    'host.rules.3': 'Pique d’en haut : sa traînée devient la tienne.',
    'host.rules.skip': 'Passer',
    'host.rules.phonesOk': '{n}/{total} téléphones prêts',

    // ─── HUD ───
    'host.phase.countdown': 'Envol',
    'host.phase.noon': 'Midi',
    'host.phase.afternoon': 'Après-midi',
    'host.phase.golden': 'Heure dorée',
    'host.phase.sunset': 'Couchant',
    'host.phase.greatShadow': 'La Grande Ombre',
    'host.phase.night': 'Nuit',
    'host.phase.over': 'Nuit',
    'host.phaseHint.golden': 'Vole nord-sud, en travers de ton ombre : elle balaie large.',
    'host.phaseHint.greatShadow': 'La nuit fige le sable. File vers l’est !',
    'host.countdown.go': 'Envol !',
    'host.hud.round': 'Manche',
    'host.hud.double': 'compte double',
    'host.banner.lastRound': 'Dernier couchant',
    'host.banner.lastRoundSub': 'Cette manche compte double.',
    'host.banner.round': 'Manche {n}',

    // ─── Toasts ───
    'host.toast.joined': '{name} rejoint le désert',
    'host.toast.left': '{name} a perdu la connexion',
    'host.toast.substitute': 'Un bot garde la place de {name}',
    'host.toast.back': '{name} reprend la main',
    'host.toast.keyboard': 'Clavier {n} dans la partie',
    'host.toast.full': 'Salle complète : 12 oiseaux',
    'host.toast.paused': '{name} a demandé une pause',
    'host.toast.fullscreen': 'F : plein écran',

    // ─── Pause ───
    'host.pause.title': 'Pause',
    'host.pause.by': 'Demandée par {name}',
    'host.pause.byPc': 'Le vent tombe. Le désert attend.',
    'host.pause.resume': 'Reprendre',
    'host.pause.settings': 'Réglages',
    'host.pause.toLobby': 'Retour au salon',
    'host.pause.confirm': 'Vraiment ? La partie sera perdue',
    'host.pause.standings': 'Manche {n} · {phase}',

    // ─── Réglages ───
    'host.settings.title': 'Réglages',
    'host.settings.sound': 'Son',
    'host.settings.image': 'Image',
    'host.settings.game': 'Jeu',
    'host.settings.keys': 'Touches',
    'host.settings.volMaster': 'Général',
    'host.settings.volMusic': 'Musique',
    'host.settings.volSfx': 'Effets',
    'host.settings.volVoice': 'Voix',
    'host.settings.quality': 'Qualité',
    'host.settings.quality.auto': 'Auto',
    'host.settings.quality.low': 'Basse',
    'host.settings.quality.medium': 'Moyenne',
    'host.settings.quality.high': 'Haute',
    'host.settings.fullscreen': 'Plein écran',
    'host.settings.reduceFlashes': 'Réduire les flashs',
    'host.settings.screenShake': 'Tremblement',
    'host.settings.lang': 'Langue',
    'host.settings.colorblind': 'Mode daltonien',
    'host.settings.narrator': 'Narrateur',
    'host.settings.narrator.voice': 'Voix',
    'host.settings.narrator.text': 'Texte',
    'host.settings.narrator.off': 'Muet',
    'host.settings.hints': 'Conseils',
    'host.settings.hints.auto': 'Auto',
    'host.settings.hints.always': 'Toujours',
    'host.settings.hints.never': 'Jamais',
    'host.settings.reset': 'Par défaut',
    'host.settings.help': 'Flèches pour choisir, Échap pour fermer',
    'host.keys.p1': 'Joueur 1',
    'host.keys.p2': 'Joueur 2',
    'host.keys.steer': 'Diriger',
    'host.keys.dive': 'Plonger (maintenir)',
    'host.keys.flap': 'Coup d’aile',
    'host.keys.join': 'Rejoindre : touche Plonger',
    'host.keys.pause': 'Pause',
    'host.keys.fullscreen': 'Plein écran',
    'host.keys.or': 'ou',
    'host.keys.solo': '(joueur seul)',
    'host.keys.numpad': 'pavé num.',
    'host.keys.note': 'Positions physiques : ZQSD en AZERTY, WASD en QWERTY.',
    'host.keys.gamepad': 'Manette : stick gauche, A Plonger, B Coup d’aile, Start Pause.',

    // ─── Résultats de manche ───
    'host.round.title': 'Manche {n}',
    'host.round.of': 'sur {total}',
    'host.round.winner': 'Le désert est à',
    'host.round.tie': 'Égalité. Le désert refuse de choisir.',
    'host.round.double': 'compte double',
    'host.round.next': 'Prochaine manche : {map}',
    'host.round.nextLast': 'Dernier couchant : {map}',
    'host.round.toMatch': 'Place au podium',
    'host.round.continue': 'Continuer',
    'host.round.ready': '{n}/{total} prêts',
    'host.round.suns': 'Soleils',
    'host.round.sunRule': '1 soleil par oiseau devancé, +{bonus} au vainqueur',
    'host.round.sunRuleDouble': '1 soleil par oiseau devancé, +{bonus} au vainqueur, ×{mult} cette manche',
    'host.round.calcBeaten1': '{n} devancé',
    'host.round.calcBeatenN': '{n} devancés',
    'host.fact.bigSteal': 'Plus gros vol : {name}, +{value} en 3\u00a0s',
    'host.fact.lastRay': 'Dernier rayon : {name}, +{value} pendant la Grande Ombre',
    'host.fact.comeback': 'Remontée : {name} partait de la dernière place',
    'host.fact.mirage': 'Mirage : {name} menait au couchant',
    'host.fact.hunter': 'Chasse : {name}, {value} piqués réussis',
    'host.fact.dodger': 'Esquive : {name} a évité {value} piqués',
    'host.fact.photoFinish': 'Photo-finish : {value} d’écart',
    'host.fact.landslide': 'Raz-de-marée : {value} d’avance',
    'host.fact.pt': '{n} pt',
    'host.fact.pts': '{n} pts',
    'host.map.parasols': 'Les Parasols',
    'host.map.aiguilles': 'Les Aiguilles',
    'host.map.geantes': 'Les Géantes',
    'host.map.cadran': 'Le Cadran',
    'host.map.lobby': 'Le salon',
    'host.plate.round': 'manche {n}',
    'host.plate.meters': '{n} m',
    'host.plate.north': 'N',
    'host.plate.winner': 'vainqueur',
    'host.plate.tie': 'égalité',

    // ─── Résultats de partie ───
    'host.match.over': 'Fin de partie',
    'host.match.wins': 'remporte la partie',
    'host.match.coWinners': 'Le désert refuse de choisir',
    'host.match.suns': 'soleils',
    'host.match.titles': 'Les titres',
    'host.match.rematch': 'Revanche',
    'host.match.toLobby': 'Salon',
    'host.match.votes': '{n}/{total} pour la revanche',
    'host.match.voteHint': 'Votez sur vos téléphones',
    'host.match.noTitle': 'Sans titre, mais pas sans panache',
    'host.match.tiebreak': 'Départagés au désert cumulé : {a} contre {b}',
    'host.stat.hits': 'Piqués',
    'host.stat.dodges': 'Esquives',
    'host.stat.stolen': 'Repris aux autres (cumulé)',
    'host.stat.low': 'En bas',
    'host.stat.roundsWon': 'Manches',

    // ─── Crédits ───
    'host.credits.title': 'Crédits',
    'host.credits.made': 'Conçu et réalisé par Claude (Anthropic)',
    'host.credits.madeSub': 'Game design, dessin, code, musique générative et mise en scène.',
    'host.credits.music': 'Musique',
    'host.credits.sfx': 'Bruitages',
    'host.credits.voice': 'Voix du conteur',
    'host.credits.voice.tts': 'Voix du narrateur synthétisée avec Pocket TTS de Kyutai (CC BY 4.0)',
    'host.credits.voice.origin': 'Voix d’origine : {name}',
    'host.credits.samples': 'Instruments échantillonnés',
    'host.credits.fonts': 'Polices',
    'host.credits.models': 'Modèles',
    'host.credits.textures': 'Textures',
    'host.credits.other': 'Ressources',
    'host.credits.tech': 'Construit avec',
    'host.credits.thanks': 'Remerciements',
    'host.credits.thanks.moebius': 'Jean Giraud, dit Moebius, dont les déserts ont inspiré celui-ci.',
    'host.credits.thanks.libre': 'Les auteurs de sons, musiques et polices libres qui partagent leur travail.',
    'host.credits.thanks.you': 'Et toi, qui as joué jusqu’à la nuit.',
    'host.credits.license': 'Licence',
    'host.credits.by': 'par',
    'host.credits.end': 'Le soleil revient toujours.',

    // ─── Reconnexion ───
    'host.reconnect.title': 'Le vent a coupé la ligne',
    'host.reconnect.body': 'Reconnexion au serveur… Les téléphones restent dans la salle.',
    'host.reconnect.lost': 'Connexion perdue. Vérifie le réseau : on réessaie sans cesse.',
  },
  en: {
    'host.back': 'Back',
    'host.close': 'Close',
    'host.yes': 'Yes',
    'host.no': 'No',
    // ─── Fallbacks (game, G6): no WebGL 2, display error ───
    'host.webgl.title': 'Ombres needs WebGL 2',
    'host.webgl.body': 'Turn on hardware acceleration in your browser settings, then reload the page.',
    'host.error.body': 'The display stopped. Reload: the game will pick up where it left off.',
    'host.error.reload': 'Reload',
    'host.key.space': 'Space',
    'host.key.enter': 'Enter',
    'host.key.esc': 'Esc',
    'host.key.shift': 'Shift',
    'host.key.altgr': 'AltGr',
    'host.key.arrows': 'Arrows',
    'host.key.tab': 'Tab',
    'host.key.altRight': 'Right Alt',
    'host.key.shiftRight': 'Right Shift',
    'host.key.numpadEnter': 'Numpad Enter',
    'host.key.numpad0': 'Numpad 0',
    'host.key.semicolon': 'Semicolon',
    'host.key.comma': 'Comma',
    'host.key.period': 'Full stop',
    'host.key.colon': 'Colon',
    'host.key.slash': 'Slash',
    'host.key.quote': 'Quote',
    'host.key.bracket': 'Bracket',
    'host.key.minus': 'Minus',
    'host.key.equal': 'Equals',

    'host.loading.start': 'Preparing the desert…',
    'host.loading.fonts': 'Inking the letters…',
    'host.loading.textures': 'Raking the sand…',
    'host.loading.models': 'Waking the birds…',
    'host.loading.sounds': 'Tuning the wind…',
    'host.loading.voices': 'The storyteller clears his throat…',
    'host.loading.shaders': 'Mixing the colours…',
    'host.loading.world': 'The sun is rising…',
    'host.loading.done': 'The desert is ready.',
    'host.loading.tagline': 'Your shadow paints the desert.',

    'host.title.pressAny': 'Press any key',
    'host.title.play': 'Play',
    'host.title.settings': 'Settings',
    'host.title.credits': 'Credits',
    'host.title.players': '1 to 12 players · one phone each',
    'host.title.scan': 'Scan to play',

    'host.lobby.title': 'The lobby',
    'host.lobby.join': 'Join',
    'host.lobby.scan': 'Scan with your phone',
    'host.lobby.orVisit': 'or open',
    'host.lobby.code': 'Room code',
    'host.lobby.connecting': 'Opening the room…',
    'host.lobby.offline': 'Server unreachable, retrying…',
    'host.lobby.keyboardJoin': 'to play on the keyboard',
    'host.lobby.keyboardJoin2': 'for a 2nd keyboard player',
    'host.lobby.players': 'The birds',
    'host.lobby.waiting': 'The desert is waiting for its birds.',
    'host.lobby.waitingSub': 'Scan the code: your bird takes off right here.',
    'host.lobby.freeSeat': 'Free seat',
    'host.lobby.addBot': 'Add a bot',
    'host.lobby.removeBot': 'Remove this bot',
    'host.lobby.changeBot': 'Change personality',
    'host.lobby.botLevel': 'Level',
    'host.lobby.ready': 'Ready',
    'host.lobby.trained': 'Trained',
    'host.lobby.substitute': 'stand-in',
    'host.lobby.disconnected': 'offline',
    'host.lobby.assist': 'Flight assist',
    'host.lobby.kind.phone': 'Phone',
    'host.lobby.kind.keyboard': 'Keyboard {n}',
    'host.lobby.kind.bot': 'Bot',
    'host.lobby.start': 'Start',
    'host.lobby.needPlayer': 'At least one player needed',
    'host.lobby.rules': 'The rules',
    'host.lobby.full': 'Full',
    'host.lobby.dummy': 'Dummy',
    'host.lobby.kbSteer': 'steer',
    'host.lobby.kbDive': 'dive',
    'host.lobby.kbFlap': 'wingbeat',
    'host.lobby.kbQuit': 'leave',
    'host.lobby.kbGoal.fly': 'Goal: fly around',
    'host.lobby.kbGoal.dive': 'Goal: hold {dive}',
    'host.lobby.kbGoal.strike': 'Goal: strike the dummy',
    'host.lobby.kbGoal.done': 'Ready: Enter to start',
    'host.goal.fly': 'Fly',
    'host.goal.dive': 'Dive',
    'host.goal.strike': 'Strike',

    'host.match.settings': 'The match',
    'host.match.rounds': 'Rounds',
    'host.match.length': 'Length',
    'host.match.length.short': 'Short',
    'host.match.length.normal': 'Normal',
    'host.match.length.long': 'Long',
    'host.match.botLevel': 'Bots',
    'host.match.lastDouble': 'Last round ×2',

    'host.bot.falcon': 'Falcon',
    'host.bot.ploughman': 'Ploughman',
    'host.bot.magpie': 'Magpie',
    'host.bot.nomad': 'Nomad',
    'host.bot.lookout': 'Lookout',
    'host.bot.fool': 'Jester',
    'host.bot.watchmaker': 'Watchmaker',
    'host.botDesc.falcon': 'hunts from above',
    'host.botDesc.ploughman': 'ploughs low and steady',
    'host.botDesc.magpie': 'raids the crown',
    'host.botDesc.nomad': 'sweeps in long lines',
    'host.botDesc.lookout': 'lurks in tower shade',
    'host.botDesc.fool': 'unpredictable',
    'host.botDesc.watchmaker': 'seals its sand before night',
    'host.botLevel.0': 'Fledgling',
    'host.botLevel.1': 'Wanderer',
    'host.botLevel.2': 'Sand Lord',

    'host.rules.title': 'Three rules to start with',
    'host.rules.1': 'Your shadow paints the sand. At nightfall, we count.',
    'host.rules.2': 'Low: strong. High: wide. Strong covers pale.',
    'host.rules.3': 'Strike from above: their trail becomes yours.',
    'host.rules.skip': 'Skip',
    'host.rules.phonesOk': '{n}/{total} phones ready',

    'host.phase.countdown': 'Take-off',
    'host.phase.noon': 'Noon',
    'host.phase.afternoon': 'Afternoon',
    'host.phase.golden': 'Golden hour',
    'host.phase.sunset': 'Sunset',
    'host.phase.greatShadow': 'The Great Shadow',
    'host.phase.night': 'Night',
    'host.phase.over': 'Night',
    'host.phaseHint.golden': 'Fly north–south, across your shadow: it sweeps wide.',
    'host.phaseHint.greatShadow': 'Night freezes the sand. Head east!',
    'host.countdown.go': 'Take off!',
    'host.hud.round': 'Round',
    'host.hud.double': 'counts double',
    'host.banner.lastRound': 'Last sunset',
    'host.banner.lastRoundSub': 'This round counts double.',
    'host.banner.round': 'Round {n}',

    'host.toast.joined': '{name} joins the desert',
    'host.toast.left': '{name} lost connection',
    'host.toast.substitute': 'A bot keeps {name}’s seat warm',
    'host.toast.back': '{name} takes back control',
    'host.toast.keyboard': 'Keyboard {n} is in',
    'host.toast.full': 'Room full: 12 birds',
    'host.toast.paused': '{name} called a pause',
    'host.toast.fullscreen': 'F: fullscreen',

    'host.pause.title': 'Paused',
    'host.pause.by': 'Called by {name}',
    'host.pause.byPc': 'The wind drops. The desert waits.',
    'host.pause.resume': 'Resume',
    'host.pause.settings': 'Settings',
    'host.pause.toLobby': 'Back to lobby',
    'host.pause.confirm': 'Sure? The match will be lost',
    'host.pause.standings': 'Round {n} · {phase}',

    'host.settings.title': 'Settings',
    'host.settings.sound': 'Sound',
    'host.settings.image': 'Display',
    'host.settings.game': 'Game',
    'host.settings.keys': 'Keys',
    'host.settings.volMaster': 'Master',
    'host.settings.volMusic': 'Music',
    'host.settings.volSfx': 'Effects',
    'host.settings.volVoice': 'Voice',
    'host.settings.quality': 'Quality',
    'host.settings.quality.auto': 'Auto',
    'host.settings.quality.low': 'Low',
    'host.settings.quality.medium': 'Medium',
    'host.settings.quality.high': 'High',
    'host.settings.fullscreen': 'Fullscreen',
    'host.settings.reduceFlashes': 'Reduce flashes',
    'host.settings.screenShake': 'Screen shake',
    'host.settings.lang': 'Language',
    'host.settings.colorblind': 'Colour-blind mode',
    'host.settings.narrator': 'Narrator',
    'host.settings.narrator.voice': 'Voice',
    'host.settings.narrator.text': 'Text',
    'host.settings.narrator.off': 'Off',
    'host.settings.hints': 'Tips',
    'host.settings.hints.auto': 'Auto',
    'host.settings.hints.always': 'Always',
    'host.settings.hints.never': 'Never',
    'host.settings.reset': 'Defaults',
    'host.settings.help': 'Arrows to choose, Esc to close',
    'host.keys.p1': 'Player 1',
    'host.keys.p2': 'Player 2',
    'host.keys.steer': 'Steer',
    'host.keys.dive': 'Dive (hold)',
    'host.keys.flap': 'Wingbeat',
    'host.keys.join': 'Join: press Dive',
    'host.keys.pause': 'Pause',
    'host.keys.fullscreen': 'Fullscreen',
    'host.keys.or': 'or',
    'host.keys.solo': '(single player)',
    'host.keys.numpad': 'numpad',
    'host.keys.note': 'Physical key positions: WASD on QWERTY, ZQSD on AZERTY.',
    'host.keys.gamepad': 'Gamepad: left stick, A Dive, B Wingbeat, Start Pause.',

    'host.round.title': 'Round {n}',
    'host.round.of': 'of {total}',
    'host.round.winner': 'The desert belongs to',
    'host.round.tie': 'A tie. The desert refuses to choose.',
    'host.round.double': 'counts double',
    'host.round.next': 'Next round: {map}',
    'host.round.nextLast': 'Last sunset: {map}',
    'host.round.toMatch': 'On to the podium',
    'host.round.continue': 'Continue',
    'host.round.ready': '{n}/{total} ready',
    'host.round.suns': 'Suns',
    'host.round.sunRule': '1 sun per bird beaten, +{bonus} to the winner',
    'host.round.sunRuleDouble': '1 sun per bird beaten, +{bonus} to the winner, ×{mult} this round',
    'host.round.calcBeaten1': '{n} beaten',
    'host.round.calcBeatenN': '{n} beaten',
    'host.fact.bigSteal': 'Biggest steal: {name}, +{value} in 3\u00a0s',
    'host.fact.lastRay': 'Last ray: {name}, +{value} during the Great Shadow',
    'host.fact.comeback': 'Comeback: {name} started from last place',
    'host.fact.mirage': 'Mirage: {name} led at sunset',
    'host.fact.hunter': 'The hunt: {name}, {value} strikes landed',
    'host.fact.dodger': 'Slippery: {name} dodged {value} strikes',
    'host.fact.photoFinish': 'Photo finish: {value} apart',
    'host.fact.landslide': 'Landslide: {value} ahead',
    'host.fact.pt': '{n} pts',
    'host.fact.pts': '{n} pts',
    'host.map.parasols': 'The Parasols',
    'host.map.aiguilles': 'The Needles',
    'host.map.geantes': 'The Giants',
    'host.map.cadran': 'The Sundial',
    'host.map.lobby': 'The lobby',
    'host.plate.round': 'round {n}',
    'host.plate.meters': '{n} m',
    'host.plate.north': 'N',
    'host.plate.winner': 'winner',
    'host.plate.tie': 'tie',

    'host.match.over': 'Match over',
    'host.match.wins': 'wins the match',
    'host.match.coWinners': 'The desert refuses to choose',
    'host.match.suns': 'suns',
    'host.match.titles': 'The titles',
    'host.match.rematch': 'Rematch',
    'host.match.toLobby': 'Lobby',
    'host.match.votes': '{n}/{total} want a rematch',
    'host.match.voteHint': 'Vote on your phones',
    'host.match.noTitle': 'No title, plenty of panache',
    'host.match.tiebreak': 'Tie broken on total desert: {a} to {b}',
    'host.stat.hits': 'Strikes',
    'host.stat.dodges': 'Dodges',
    'host.stat.stolen': 'Taken from others (total)',
    'host.stat.low': 'Low',
    'host.stat.roundsWon': 'Rounds',

    'host.credits.title': 'Credits',
    'host.credits.made': 'Designed and made by Claude (Anthropic)',
    'host.credits.madeSub': 'Game design, drawing, code, generative music and staging.',
    'host.credits.music': 'Music',
    'host.credits.sfx': 'Sound effects',
    'host.credits.voice': 'Storyteller’s voice',
    'host.credits.voice.tts': 'Narrator voice synthesised with Kyutai’s Pocket TTS (CC BY 4.0)',
    'host.credits.voice.origin': 'Original voice: {name}',
    'host.credits.samples': 'Sampled instruments',
    'host.credits.fonts': 'Fonts',
    'host.credits.models': 'Models',
    'host.credits.textures': 'Textures',
    'host.credits.other': 'Resources',
    'host.credits.tech': 'Built with',
    'host.credits.thanks': 'Thanks',
    'host.credits.thanks.moebius': 'Jean Giraud, known as Moebius, whose deserts inspired this one.',
    'host.credits.thanks.libre': 'The authors of free sounds, music and fonts who share their work.',
    'host.credits.thanks.you': 'And you, for playing until nightfall.',
    'host.credits.license': 'Licence',
    'host.credits.by': 'by',
    'host.credits.end': 'The sun always comes back.',

    'host.reconnect.title': 'The wind cut the line',
    'host.reconnect.body': 'Reconnecting to the server… Phones stay in the room.',
    'host.reconnect.lost': 'Connection lost. Check the network: we keep retrying.',
  },
}
