import type { StringTable } from './index.ts'

// Chaînes de la page d'accueil mobile (/m, src/landing). Volontairement absente de STRING_TABLES :
// la page importe ce seul fichier (pas tout l'i18n du jeu) pour rester légère.
export const landing: StringTable = {
  fr: {
    'landing.title': 'Ombres : un party game où ton téléphone est la manette',
    'landing.pitch': 'Ton ombre peint le désert. À la nuit, le plus grand territoire gagne.',
    'landing.intro': 'Un party game pour le salon. Tu chevauches un oiseau géant au-dessus du désert pendant que le soleil se couche. De 1 à 12 joueurs, un téléphone chacun.',
    'landing.media.trailer': 'Bande-annonce',
    'landing.media.soundOn': 'Activer le son',
    'landing.media.soundOff': 'Couper le son',
    'landing.media.play': 'Lecture',
    'landing.media.pause': 'Pause',
    'landing.media.shots': 'Captures du jeu',
    'landing.media.dot': 'Image {n} sur {total}',
    'landing.big.title': 'À jouer sur grand écran',
    'landing.big.body': 'Ouvre {url} sur un ordinateur ou une TV : ton téléphone sera la manette.',
    'landing.big.note': 'Gratuit, dans le navigateur (Chrome, Edge ou Firefox). Rien à installer, pas de compte.',
    'landing.big.copy': 'Copier le lien',
    'landing.big.copied': 'Lien copié',
    'landing.big.copyFail': 'Copie impossible : note l’adresse ci-dessus',
    'landing.big.share': 'Partager',
    'landing.big.shareText': 'Ombres : un party game où ton téléphone sert de manette. À ouvrir sur un ordinateur ou une TV.',
    'landing.desk.title': 'Tu es sur grand écran',
    'landing.desk.body': 'Lance le jeu ici. Les joueurs scanneront le QR code avec leur téléphone.',
    'landing.desk.play': 'Lancer le jeu',
    'landing.code.title': 'Tu as un code de salle ?',
    'landing.code.body': 'Un ami lance la partie ? Tape les quatre lettres affichées sur son écran, ou scanne le QR code avec l’appareil photo.',
    'landing.code.label': 'Code de salle, 4 lettres',
    'landing.code.join': 'Rejoindre',
    'landing.strip.title': 'Une manche en quatre cases',
    'landing.strip.1': 'Le grand écran affiche un QR code. Chacun le scanne et choisit sa couleur.',
    'landing.strip.2': 'Ton téléphone devient la manette : le joystick pour diriger, PLONGER maintenu pour raser le sable.',
    'landing.strip.3': 'Ton ombre peint le sable à ta couleur. Plonge sur un oiseau plus bas pour voler sa traînée.',
    'landing.strip.4': 'Le soleil se couche, la nuit descend de la falaise et fige tout. Le plus de sable gagne.',
    'landing.fact.players': '1 à 12 joueurs',
    'landing.fact.length': 'Trois manches, sept minutes',
    'landing.fact.bots': 'Des bots si tu joues seul',
    'landing.fact.free': 'Gratuit, sans pub',
    'landing.credits': 'Conçu et réalisé par Claude (Anthropic), sous la supervision de Brieuc Crosson. Musiques : Alexandr Zhelanov et Tri-Tachyon (CC BY 4.0), cynicmusic et isaiah658 (CC0). Voix du narrateur : Qwen3-TTS (Apache 2.0) et Pocket TTS de Kyutai (CC BY 4.0). Polices sous licence SIL OFL.',
    'landing.github': 'Code source sur GitHub',
    'landing.forceGame': 'Ouvrir quand même le jeu complet',
    'landing.here.note': 'Ce téléphone ou cette tablette sert d’écran ? Lance le jeu ici, de préférence à l’horizontale : les autres joueurs scanneront le QR code affiché dessus.',
    'landing.here.open': 'Ouvrir le jeu ici quand même',
    'landing.otherLang': 'English',
  },
  en: {
    'landing.title': 'Ombres: a party game where your phone is the controller',
    'landing.pitch': 'Your shadow paints the desert. At nightfall, the biggest territory wins.',
    'landing.intro': 'A party game for the living room. You ride a giant bird over the desert while the sun goes down. 1 to 12 players, one phone each.',
    'landing.media.trailer': 'Trailer',
    'landing.media.soundOn': 'Turn sound on',
    'landing.media.soundOff': 'Mute',
    'landing.media.play': 'Play',
    'landing.media.pause': 'Pause',
    'landing.media.shots': 'Screenshots',
    'landing.media.dot': 'Image {n} of {total}',
    'landing.big.title': 'Play it on a big screen',
    'landing.big.body': 'Open {url} on a computer or a TV: your phone will be the controller.',
    'landing.big.note': 'Free, in the browser (Chrome, Edge or Firefox). Nothing to install, no account.',
    'landing.big.copy': 'Copy the link',
    'landing.big.copied': 'Link copied',
    'landing.big.copyFail': 'Can’t copy: note the address above',
    'landing.big.share': 'Share',
    'landing.big.shareText': 'Ombres: a party game where your phone is the controller. Open it on a computer or a TV.',
    'landing.desk.title': 'You’re on a big screen',
    'landing.desk.body': 'Start the game here. Players scan the QR code with their phones.',
    'landing.desk.play': 'Start the game',
    'landing.code.title': 'Got a room code?',
    'landing.code.body': 'A friend is hosting? Type the four letters shown on their screen, or scan the QR code with your camera.',
    'landing.code.label': 'Room code, 4 letters',
    'landing.code.join': 'Join',
    'landing.strip.title': 'A round in four panels',
    'landing.strip.1': 'The big screen shows a QR code. Everyone scans it and picks a colour.',
    'landing.strip.2': 'Your phone becomes the controller: the stick steers, hold DIVE to skim the sand.',
    'landing.strip.3': 'Your shadow paints the sand in your colour. Dive onto a lower bird to steal its trail.',
    'landing.strip.4': 'The sun sets, night sweeps in from the cliff and freezes everything. Most sand wins.',
    'landing.fact.players': '1 to 12 players',
    'landing.fact.length': 'Three rounds, seven minutes',
    'landing.fact.bots': 'Bots if you play alone',
    'landing.fact.free': 'Free, no ads',
    'landing.credits': 'Designed and built by Claude (Anthropic), supervised by Brieuc Crosson. Music by Alexandr Zhelanov and Tri-Tachyon (CC BY 4.0), cynicmusic and isaiah658 (CC0). Narrator voices: Qwen3-TTS (Apache 2.0) and Kyutai’s Pocket TTS (CC BY 4.0). Fonts under the SIL OFL.',
    'landing.github': 'Source code on GitHub',
    'landing.forceGame': 'Open the full game anyway',
    'landing.here.note': 'Is this phone or tablet the screen? Start the game here, ideally in landscape: the other players will scan the QR code it shows.',
    'landing.here.open': 'Open the game here anyway',
    'landing.otherLang': 'Français',
  },
}
