import type { StringTable } from './index.ts'

// Chaînes du domaine « phone » (app manette). Clés préfixées par « phone. ».
// Ton : court, direct, tutoiement ; les noms des boutons (PLONGER, COUP D'AILE) sont ceux de la TV.
// Glossaire EN (docs/polish/ORDERS.md §9) : DIVE = le bouton tenu (voler bas) ; l'attaque d'en haut =
// strike / strikes / STRIKE ; COUP D'AILE = WINGBEAT. Jamais « dive » pour l'attaque.
export const phone: StringTable = {
  fr: {
    'phone.title': 'Ombres — manette',
    'phone.names':
      'Mirage,Sirocco,Fennec,Oasis,Gecko,Zéphyr,Silex,Dune,Méhari,Khamsin,Chergui,Harmattan,Scarabée,Caravane,Tamaris,Agave,Onyx,Nopal,Saguaro,Ocelle,Sahel,Alizé,Mistral,Sable',

    // Rejoindre / connexion
    'phone.join.title': 'Rejoindre la partie',
    'phone.join.prompt': 'Tape le code affiché sur l’écran.',
    'phone.join.go': 'Rejoindre',
    'phone.join.placeholder': 'CODE',
    'phone.connecting': 'Connexion à la salle',
    'phone.searching': 'On cherche la salle…',
    'phone.waitingHost': 'En attente de l’écran…',
    'phone.waitingHost.body': 'Garde cette page ouverte : la partie s’affiche dès que l’écran répond.',
    'phone.hostAway.title': 'L’écran se reconnecte…',
    'phone.hostAway.body': 'Garde ta manette en main : la partie reprend toute seule.',
    'phone.reconnect.title': 'Le vent t’a emporté…',
    'phone.reconnect.body': 'Reconnexion en cours',

    // Erreurs
    'phone.error.room-not-found.title': 'Salle introuvable',
    'phone.error.room-not-found.body': 'Vérifie le code affiché sur l’écran de jeu.',
    'phone.error.room-not-found.discover': 'Pas de partie en cours ?',
    'phone.error.room-not-found.discoverLink': 'Découvrir Ombres',
    'phone.error.room-full.title': 'La salle est pleine',
    'phone.error.room-full.body': 'Douze oiseaux volent déjà. Attends qu’une place se libère.',
    'phone.error.kicked.title': 'Tu as été retiré de la partie',
    'phone.error.kicked.body': 'L’écran t’a retiré du salon. Tu peux revenir quand tu veux.',
    'phone.error.replaced.title': 'Manette ouverte ailleurs',
    'phone.error.replaced.body': 'Cette manette est déjà active dans un autre onglet.',
    'phone.error.bad-request.title': 'Oups',
    'phone.error.bad-request.body': 'La connexion a échoué. Réessaie dans un instant.',
    'phone.error.retry': 'Réessayer',
    'phone.error.rejoin': 'Revenir dans la partie',
    'phone.error.takeBack': 'Utiliser cette manette',

    // Profil
    'phone.profile.title': 'Qui vole ?',
    'phone.profile.name': 'Ton nom',
    'phone.profile.reroll': 'Un autre nom',
    'phone.profile.color': 'Ta couleur',
    'phone.profile.more': 'Plus de couleurs',
    'phone.profile.less': 'Moins de couleurs',
    'phone.profile.go': 'Prendre mon envol',
    'phone.profile.save': 'Valider',
    'phone.profile.hint': 'Ton ombre peindra le désert en {color}.',
    'phone.profile.taken': 'prise',

    // Salon
    'phone.lobby.room': 'Salle',
    'phone.lobby.practice': 'Entraîne-toi',
    'phone.lobby.allDone': 'Prêt à jouer ! Continue à voler en attendant.',
    'phone.goal.fly': 'Vole',
    'phone.goal.fly.how': 'Bouge le joystick : ton oiseau vole sur l’écran.',
    'phone.goal.dive': 'Plonge',
    'phone.goal.dive.how': 'Maintiens PLONGER : petite ombre, qui peint fort.',
    'phone.goal.strike': 'Pique',
    'phone.goal.strike.how': 'Relâche pour monter, puis pique sur le mannequin.',
    'phone.lobby.start': 'Lancer la partie',
    'phone.lobby.startShort': 'Lancer',
    'phone.lobby.waitLeader': 'C’est {name} qui lance la partie',
    'phone.lobby.waitScreen': 'La partie se lance depuis l’écran',
    'phone.lobby.thumbHere': 'Pouce ici',
    'phone.lobby.watch': 'Ton oiseau vole sur l’écran',

    // Commandes
    'phone.btn.dive': 'Plonger',
    'phone.btn.strike': 'Piquer',
    'phone.btn.diving': 'Piqué !',
    'phone.btn.flap': 'Coup d’aile',
    'phone.btn.flapShort': 'Coup d’aile',
    'phone.pause.hold': 'Maintiens pour la pause',
    'phone.relative.hint': 'Gauche / droite pour tourner',
    'phone.tilt.hint': 'Penche le téléphone pour diriger',
    'phone.tilt.enable': 'Activer l’inclinaison',
    'phone.tilt.recalibrate': 'Recalibrer',
    'phone.tilt.unavailable': 'Inclinaison indisponible',
    'phone.tilt.denied': 'Autorisation refusée',

    // En jeu
    'phone.band.score': 'Rang et part du désert',
    'phone.play.go': 'Envol !',
    'phone.play.clac': 'COUP D’AILE !',
    'phone.play.stunned': 'Décroché !',
    'phone.play.hidden': 'Caché',
    'phone.play.night': 'Dans la nuit',
    'phone.play.immune': 'Intouchable',
    'phone.fx.hit': 'Touché !',
    'phone.fx.stunned': 'Décroché !',
    'phone.fx.dodge': 'Esquivé !',
    'phone.fx.planted': 'Raté…',
    'phone.fx.crown': 'Couronne !',
    'phone.fx.win': 'Victoire !',
    'phone.rotate': 'Tourne ton téléphone',

    // Cartes des règles (GDD §2)
    'phone.card.1': 'Ton ombre peint le sable. À la nuit, on compte.',
    'phone.card.2': 'Bas : fort. Haut : grand. Le fort recouvre le pâle.',
    'phone.card.3': 'Pique d’en haut : sa traînée devient la tienne.',

    // Avant la manche
    'phone.intro.round': 'Manche {n} sur {total}',
    'phone.intro.double': 'Dernier couchant : il compte double !',
    'phone.intro.ok': 'Compris !',
    'phone.intro.waiting': '{ok} sur {total} prêts',
    'phone.map.parasols': 'Les Parasols',
    'phone.map.aiguilles': 'Les Aiguilles',
    'phone.map.geantes': 'Les Géantes',
    'phone.map.cadran': 'Le Cadran',
    'phone.map.lobby': 'Le Salon',

    // Entre les manches
    'phone.roundEnd.title': 'Fin de la manche {n}',
    'phone.roundEnd.ofDesert': 'du désert',
    'phone.roundEnd.rankOf': 'sur {n}',
    'phone.roundEnd.suns.one': '+{n} soleil',
    'phone.roundEnd.suns.other': '+{n} soleils',
    'phone.roundEnd.suns.zero': 'Aucun soleil',
    'phone.roundEnd.total': 'Total : {n}',
    'phone.roundEnd.totalRank': '{rank} au classement',
    'phone.roundEnd.winner': 'Le désert est à {name}',
    'phone.roundEnd.youWin': 'Le désert est à toi !',
    'phone.roundEnd.nextDouble': 'La prochaine manche compte double.',
    'phone.stat.hits': 'Piqués réussis',
    'phone.stat.gotHit': 'Décrochages subis',
    'phone.stat.dodges': 'Esquives',
    'phone.stat.misses': 'Piqués ratés',
    'phone.stat.stolen': 'Pris aux autres',
    'phone.stat.lowFrac': 'Au ras du sable',
    'phone.stat.hidden': 'Caché',
    'phone.stat.seconds': '{n} s',
    'phone.ready': 'Prêt !',
    'phone.ready.done': 'C’est noté',
    'phone.ready.count': '{n} sur {total} prêts',

    // Fin de partie
    'phone.matchEnd.title': 'Fin de la partie',
    'phone.matchEnd.youWin': 'Tu gagnes la partie !',
    'phone.matchEnd.winner': '{name} gagne la partie',
    'phone.matchEnd.tie': 'Le désert refuse de choisir',
    'phone.matchEnd.yourTitle': 'Ton titre',
    'phone.matchEnd.noTitle': 'Pas de titre cette fois. Le désert t’a à l’œil.',
    'phone.matchEnd.rank': '{rank} sur {of}',
    'phone.matchEnd.suns.one': '{n} soleil',
    'phone.matchEnd.suns.other': '{n} soleils',
    'phone.matchEnd.rematch': 'Revanche',
    'phone.matchEnd.lobby': 'Salon',
    'phone.matchEnd.votes': '{n} sur {total}',
    'phone.matchEnd.voted': 'Vote envoyé',

    // Arrivé en cours de partie
    'phone.spectate.title': 'Partie en cours',
    'phone.spectate.body': 'Tu entres en piste à la prochaine manche. Regarde l’écran en attendant !',
    'phone.spectate.round': 'Manche {n} sur {total}',

    // Pause
    'phone.pause.title': 'Pause',
    'phone.pause.by': 'Mise en pause par {name}',
    'phone.pause.byScreen': 'Mise en pause depuis l’écran',
    'phone.pause.resume': 'Reprendre',
    'phone.pause.waitResume': 'La partie reprendra depuis l’écran.',

    // Réglages
    'phone.settings.title': 'Réglages',
    'phone.settings.open': 'Réglages',
    'phone.settings.close': 'Fermer',
    'phone.settings.profile': 'Changer de nom ou de couleur',
    'phone.settings.controls': 'Contrôle',
    'phone.scheme.absolute': 'Absolu',
    'phone.scheme.absolute.desc': 'Le joystick montre où aller sur l’écran : en haut, c’est le nord.',
    'phone.scheme.relative': 'Relatif',
    'phone.scheme.relative.desc': 'Gauche et droite font tourner l’oiseau, comme un volant.',
    'phone.scheme.tilt': 'Inclinaison',
    'phone.scheme.tilt.desc': 'Penche le téléphone vers où aller. Les boutons restent tactiles.',
    'phone.settings.assist': 'Aide au vol',
    'phone.settings.assist.desc': 'Piqués plus faciles, esquive automatique une fois sur deux. Une plume s’affiche à côté de ton nom.',
    'phone.settings.haptics': 'Vibrations',
    'phone.settings.rules': 'Les règles',
  },
  en: {
    'phone.title': 'Ombres — controller',
    'phone.names':
      'Mirage,Sirocco,Fennec,Oasis,Gecko,Zephyr,Flint,Dune,Mehari,Khamsin,Chergui,Harmattan,Scarab,Caravan,Tamarisk,Agave,Onyx,Nopal,Saguaro,Ocelot,Simoom,Mistral,Mesa,Sahel',

    'phone.join.title': 'Join the game',
    'phone.join.prompt': 'Enter the code shown on the screen.',
    'phone.join.go': 'Join',
    'phone.join.placeholder': 'CODE',
    'phone.connecting': 'Connecting to room',
    'phone.searching': 'Looking for the room…',
    'phone.waitingHost': 'Waiting for the screen…',
    'phone.waitingHost.body': 'Keep this page open: the game shows up as soon as the screen answers.',
    'phone.hostAway.title': 'The screen is reconnecting…',
    'phone.hostAway.body': 'Hold on to your controller: the game will resume on its own.',
    'phone.reconnect.title': 'The wind carried you off…',
    'phone.reconnect.body': 'Reconnecting',

    'phone.error.room-not-found.title': 'Room not found',
    'phone.error.room-not-found.body': 'Check the code shown on the game screen.',
    'phone.error.room-not-found.discover': 'No game running?',
    'phone.error.room-not-found.discoverLink': 'Discover Ombres',
    'phone.error.room-full.title': 'The room is full',
    'phone.error.room-full.body': 'Twelve birds are already flying. Wait for a spot to open up.',
    'phone.error.kicked.title': 'You were removed from the game',
    'phone.error.kicked.body': 'The screen removed you from the lobby. You can come back anytime.',
    'phone.error.replaced.title': 'Controller open elsewhere',
    'phone.error.replaced.body': 'This controller is already active in another tab.',
    'phone.error.bad-request.title': 'Oops',
    'phone.error.bad-request.body': 'The connection failed. Try again in a moment.',
    'phone.error.retry': 'Try again',
    'phone.error.rejoin': 'Rejoin the game',
    'phone.error.takeBack': 'Use this controller',

    'phone.profile.title': 'Who’s flying?',
    'phone.profile.name': 'Your name',
    'phone.profile.reroll': 'Another name',
    'phone.profile.color': 'Your colour',
    'phone.profile.more': 'More colours',
    'phone.profile.less': 'Fewer colours',
    'phone.profile.go': 'Take off',
    'phone.profile.save': 'Save',
    'phone.profile.hint': 'Your shadow will paint the desert {color}.',
    'phone.profile.taken': 'taken',

    'phone.lobby.room': 'Room',
    'phone.lobby.practice': 'Practice',
    'phone.lobby.allDone': 'Ready to play! Keep flying while you wait.',
    'phone.goal.fly': 'Fly',
    'phone.goal.fly.how': 'Move the joystick: your bird flies on the screen.',
    'phone.goal.dive': 'Dive',
    'phone.goal.dive.how': 'Hold DIVE: a small shadow that paints strong.',
    'phone.goal.strike': 'Strike',
    'phone.goal.strike.how': 'Release to climb, then strike the dummy from above.',
    'phone.lobby.start': 'Start the game',
    'phone.lobby.startShort': 'Start',
    'phone.lobby.waitLeader': '{name} will start the game',
    'phone.lobby.waitScreen': 'The game starts from the screen',
    'phone.lobby.thumbHere': 'Thumb here',
    'phone.lobby.watch': 'Your bird is flying on the screen',

    'phone.btn.dive': 'Dive',
    'phone.btn.strike': 'Strike',
    'phone.btn.diving': 'Striking!',
    'phone.btn.flap': 'Wingbeat',
    'phone.btn.flapShort': 'Wingbeat',
    'phone.pause.hold': 'Hold to pause',
    'phone.relative.hint': 'Left / right to turn',
    'phone.tilt.hint': 'Tilt the phone to steer',
    'phone.tilt.enable': 'Enable tilt',
    'phone.tilt.recalibrate': 'Recalibrate',
    'phone.tilt.unavailable': 'Tilt unavailable',
    'phone.tilt.denied': 'Permission denied',

    'phone.band.score': 'Rank and share of the desert',
    'phone.play.go': 'Take off!',
    'phone.play.clac': 'WINGBEAT!',
    'phone.play.stunned': 'Knocked out!',
    'phone.play.hidden': 'Hidden',
    'phone.play.night': 'In the night',
    'phone.play.immune': 'Untouchable',
    'phone.fx.hit': 'Hit!',
    'phone.fx.stunned': 'Knocked out!',
    'phone.fx.dodge': 'Dodged!',
    'phone.fx.planted': 'Missed…',
    'phone.fx.crown': 'Crown!',
    'phone.fx.win': 'Victory!',
    'phone.rotate': 'Turn your phone sideways',

    'phone.card.1': 'Your shadow paints the sand. At nightfall, we count.',
    'phone.card.2': 'Low: strong. High: wide. Strong covers pale.',
    'phone.card.3': 'Strike from above: their trail becomes yours.',

    'phone.intro.round': 'Round {n} of {total}',
    'phone.intro.double': 'Last sunset: it counts double!',
    'phone.intro.ok': 'Got it!',
    'phone.intro.waiting': '{ok} of {total} ready',
    'phone.map.parasols': 'The Parasols',
    'phone.map.aiguilles': 'The Needles',
    'phone.map.geantes': 'The Giants',
    'phone.map.cadran': 'The Sundial',
    'phone.map.lobby': 'The Lobby',

    'phone.roundEnd.title': 'End of round {n}',
    'phone.roundEnd.ofDesert': 'of the desert',
    'phone.roundEnd.rankOf': 'of {n}',
    'phone.roundEnd.suns.one': '+{n} sun',
    'phone.roundEnd.suns.other': '+{n} suns',
    'phone.roundEnd.suns.zero': 'No suns',
    'phone.roundEnd.total': 'Total: {n}',
    'phone.roundEnd.totalRank': '{rank} overall',
    'phone.roundEnd.winner': 'The desert belongs to {name}',
    'phone.roundEnd.youWin': 'The desert is yours!',
    'phone.roundEnd.nextDouble': 'The next round counts double.',
    'phone.stat.hits': 'Strikes landed',
    'phone.stat.gotHit': 'Times knocked out',
    'phone.stat.dodges': 'Dodges',
    'phone.stat.misses': 'Missed strikes',
    'phone.stat.stolen': 'Taken from others',
    'phone.stat.lowFrac': 'Flying low',
    'phone.stat.hidden': 'Hidden',
    'phone.stat.seconds': '{n} s',
    'phone.ready': 'Ready!',
    'phone.ready.done': 'Got it',
    'phone.ready.count': '{n} of {total} ready',

    'phone.matchEnd.title': 'Match over',
    'phone.matchEnd.youWin': 'You win the match!',
    'phone.matchEnd.winner': '{name} wins the match',
    'phone.matchEnd.tie': 'The desert refuses to choose',
    'phone.matchEnd.yourTitle': 'Your title',
    'phone.matchEnd.noTitle': 'No title this time. The desert is keeping an eye on you.',
    'phone.matchEnd.rank': '{rank} of {of}',
    'phone.matchEnd.suns.one': '{n} sun',
    'phone.matchEnd.suns.other': '{n} suns',
    'phone.matchEnd.rematch': 'Rematch',
    'phone.matchEnd.lobby': 'Lobby',
    'phone.matchEnd.votes': '{n} of {total}',
    'phone.matchEnd.voted': 'Vote sent',

    'phone.spectate.title': 'Game in progress',
    'phone.spectate.body': 'You’ll join at the next round. Watch the screen in the meantime!',
    'phone.spectate.round': 'Round {n} of {total}',

    'phone.pause.title': 'Paused',
    'phone.pause.by': 'Paused by {name}',
    'phone.pause.byScreen': 'Paused from the screen',
    'phone.pause.resume': 'Resume',
    'phone.pause.waitResume': 'The game will resume from the screen.',

    'phone.settings.title': 'Settings',
    'phone.settings.open': 'Settings',
    'phone.settings.close': 'Close',
    'phone.settings.profile': 'Change name or colour',
    'phone.settings.controls': 'Controls',
    'phone.scheme.absolute': 'Absolute',
    'phone.scheme.absolute.desc': 'The stick points where to go on the screen: up is north.',
    'phone.scheme.relative': 'Relative',
    'phone.scheme.relative.desc': 'Left and right turn the bird, like a steering wheel.',
    'phone.scheme.tilt': 'Tilt',
    'phone.scheme.tilt.desc': 'Lean the phone where you want to go. Buttons stay on screen.',
    'phone.settings.assist': 'Flight assist',
    'phone.settings.assist.desc': 'Easier strikes, automatic dodge half the time. A feather shows next to your name.',
    'phone.settings.haptics': 'Vibration',
    'phone.settings.rules': 'The rules',
  },
}
