import type { StringTable } from './index.ts'

// Chaînes du domaine « titles » : les 12 titres de fin de partie (GDD §11.4).
// Pour chaque titre : .name (nom), .desc (courte description, sans pronom
// genré), .stat (le chiffre ; {n} est déjà mis en forme : « 4 », « 12,3 % », « 18 s »).
export const titles: StringTable = {
  fr: {
    'titles.rapace.name': 'Le Rapace',
    'titles.rapace.desc': 'Tombe du ciel, et jamais pour rien.',
    'titles.rapace.stat': '{n} piqués réussis',
    'titles.gibier.name': 'Le Gibier',
    'titles.gibier.desc': 'La cible préférée de toutes les serres.',
    'titles.gibier.stat': '{n} décrochages subis',
    'titles.anguille.name': 'L’Anguille',
    'titles.anguille.desc': 'Glisse entre les serres au dernier moment.',
    'titles.anguille.stat': '{n} esquives réussies',
    'titles.kamikaze.name': 'Le Kamikaze',
    'titles.kamikaze.desc': 'Le sable connaît ce visage par cœur.',
    'titles.kamikaze.stat': '{n} piqués dans le sable',
    'titles.pilleur.name': 'Le Pilleur',
    'titles.pilleur.desc': 'Le sable des autres a meilleur goût.',
    'titles.pilleur.stat': '{n} du désert pris aux autres',
    'titles.raseMottes.name': 'Rase-Mottes',
    'titles.raseMottes.desc': 'Vole si bas que le sable en rougit.',
    'titles.raseMottes.stat': '{n} du temps au ras du sable',
    'titles.nuage.name': 'Le Nuage',
    'titles.nuage.desc': 'Toujours plus haut, toujours plus pâle.',
    'titles.nuage.stat': '{n} du temps en altitude',
    'titles.batisseur.name': 'Le Bâtisseur',
    'titles.batisseur.desc': 'Tout était déjà construit à midi.',
    'titles.batisseur.stat': '{n} du territoire final acquis dès l’après-midi',
    'titles.notaire.name': 'Le Notaire',
    'titles.notaire.desc': 'Scelle son sable à l’ombre des tours.',
    'titles.notaire.stat': '{n} du désert scellé sous les tours',
    'titles.dernierRayon.name': 'Dernier Rayon',
    'titles.dernierRayon.desc': 'Vole la dernière lumière du jour.',
    'titles.dernierRayon.stat': '+{n} pendant la Grande Ombre',
    'titles.lezard.name': 'Le Lézard',
    'titles.lezard.desc': 'Rien ne vaut l’ombre d’une tour.',
    'titles.lezard.stat': '{n} à l’ombre des tours',
    'titles.revenant.name': 'Le Revenant',
    'titles.revenant.desc': 'Revient de loin, au tout dernier moment.',
    'titles.revenant.stat': '+{n} places dans la dernière ligne droite',
  },
  en: {
    'titles.rapace.name': 'The Raptor',
    'titles.rapace.desc': 'Drops from the sky, never for nothing.',
    'titles.rapace.stat': '{n} dives landed',
    'titles.gibier.name': 'The Quarry',
    'titles.gibier.desc': 'Every talon’s favourite target.',
    'titles.gibier.stat': 'knocked down {n} times',
    'titles.anguille.name': 'The Eel',
    'titles.anguille.desc': 'Slips through the talons at the last moment.',
    'titles.anguille.stat': '{n} dodges',
    'titles.kamikaze.name': 'The Kamikaze',
    'titles.kamikaze.desc': 'The sand knows that face by heart.',
    'titles.kamikaze.stat': '{n} dives into the sand',
    'titles.pilleur.name': 'The Plunderer',
    'titles.pilleur.desc': 'Other people’s sand tastes better.',
    'titles.pilleur.stat': '{n} of the desert taken from others',
    'titles.raseMottes.name': 'The Hedgehopper',
    'titles.raseMottes.desc': 'Flies so low the sand blushes.',
    'titles.raseMottes.stat': '{n} of the time skimming the sand',
    'titles.nuage.name': 'The Cloud',
    'titles.nuage.desc': 'Ever higher, ever paler.',
    'titles.nuage.stat': '{n} of the time up high',
    'titles.batisseur.name': 'The Builder',
    'titles.batisseur.desc': 'It was all built by noon.',
    'titles.batisseur.stat': '{n} of the final territory held since the afternoon',
    'titles.notaire.name': 'The Notary',
    'titles.notaire.desc': 'Seals the sand in the towers’ shade.',
    'titles.notaire.stat': '{n} of the desert sealed under towers',
    'titles.dernierRayon.name': 'Last Ray',
    'titles.dernierRayon.desc': 'Steals the last light of the day.',
    'titles.dernierRayon.stat': '+{n} during the Great Shadow',
    'titles.lezard.name': 'The Lizard',
    'titles.lezard.desc': 'Nothing beats a tower’s shade.',
    'titles.lezard.stat': '{n} in the towers’ shade',
    'titles.revenant.name': 'The Revenant',
    'titles.revenant.desc': 'Comes back from nowhere, at the very end.',
    'titles.revenant.stat': '+{n} places in the final stretch',
  },
}
